- hosts: webservers

  roles:
  - role: jdauphant.nginx
    nginx_user: "www-data"
    nginx_http_params:
      - sendfile "on"
      - server_names_hash_bucket_size 512
    nginx_sites:
      as393949.net.http:
        - listen *:80
        - listen [::]:80
        - server_name as393949.net
        - return 301 "https://$host$request_uri"
      as393949.net.https:
        - listen *:443 ssl http2
        - listen [::]:443 ssl http2
        - server_name as393949.net
        - root "/srv/www/as393949.net/output"
        - index index.html
        - access_log "/var/log/nginx/as393949.net.access.log"
        - error_log "/var/log/nginx/as393949.net.error.log"
        - ssl_certificate "/etc/ssl/letsencrypt/as393949.net.crt"
        - ssl_certificate_key "/etc/ssl/letsencrypt/as393949.net.pem"
        - ssl_stapling on
        - resolver [::1] valid=300s
        - add_header Strict-Transport-Security max-age=31536000
      aurigaplatform.pw.http:
        - listen *:80
        - listen [::]:80
        - server_name aurigaplatform.pw
        - index index.php index.html
        - root "/srv/www/aurigaplatform.pw"
        - access_log "/var/log/nginx/aurigaplatform.pw.access.log"
        - error_log "/var/log/nginx/aurigaplatform.pw.error.log"
        - client_max_body_size 10M
        - location /.well-known/acme-challenge/ {
            allow all;
          }
        - location / {
            return 301 https://$host$request_uri;
          }
      aurigaplatform.pw.https:
        - listen *:443 ssl http2
        - listen [::]:443 ssl http2
        - server_name aurigaplatform.pw
        - index index.php index.html
        - root "/srv/www/aurigaplatform.pw"
        - access_log "/var/log/nginx/aurigaplatform.pw.access.log"
        - error_log "/var/log/nginx/aurigaplatform.pw.error.log"
        - ssl_certificate "/etc/ssl/letsencrypt/aurigaplatform.pw.crt"
        - ssl_certificate_key "/etc/ssl/letsencrypt/aurigaplatform.pw.pem"
        - ssl_stapling on
        - resolver [::1] valid=300s
        - client_max_body_size 10M
        - add_header Strict-Transport-Security max-age=31536000
        - location /.well-known/acme-challenge/ {
            allow all;
          }
        - location / {
            try_files $uri $uri/ /index.php?$args;
          }
        - location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires 24h;
          }
        - location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php;
          }

    nginx_configs:
      gzip:
        - gzip on
        - gzip_disable msie6
        - gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript
      ssl:
        - ssl_protocols TLSv1.2
        - ssl_prefer_server_ciphers on
        - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
        - ssl_dhparam "/etc/nginx/dhparams.pem"
        - ssl_session_timeout 1d
        - ssl_session_cache shared:SSL:50m
        - ssl_session_tickets off
      upstream:
        - upstream php { server unix:/run/php/php7.2-fpm.sock; }
