---
# This role will compile and install BIRD

- name: Create compilation and source directory
  file: path=/src/bird-1.5.0 state=directory

- name: Download BIRD source tarball
  get_url: url=ftp://bird.network.cz/pub/bird/bird-1.5.0.tar.gz dest=/src/bird-1.5.0.tar.gz

- name: Unarchive BIRD source tarball
  unarchive: src=/src/bird-1.5.0.tar.gz dest=/src/bird-1.5.0 copy=no

- name: Compile BIRD source for v4
  shell: /src/bird-1.5.0/configure && make install clean chdir=/src/bird-1.5.0

- name: Compile BIRD source for v6
  shell: /src/bird-1.5.0/configure --enable-ipv6 && make install clean chdir=/src/bird-1.5.0