---
# This role will install BIRD

- name: Make sure all packages are up to date before we install anything
  apt: update_cache=yes upgrade=safe

- name: Install BIRD package
  apt: name=bird state=latest

- name: Ensure BIRD services are started on boot
  service: name={{ item }} enabled=yes
  with_items:
     - bird
     - bird6
